export enum EtiquetaVisual {
  FUNCIONALIDAD = 'FUNCIONALIDAD',

  ITERACION = 'ITERACION',

  LISTAS = 'LISTAS',

  ESTADO = 'ESTADO',

  ATRIBUTOS = 'ATRIBUTOS',

  COMENTARIOS = 'COMENTARIOS',

  ETIQUETAS = 'ETIQUETAS',

  PRIORIDAD = 'PRIORIDAD',
}
